stages:
  - build
#  - test
  - deploy

build-job:
  stage: build
  script:
    - docker-compose build

#unit-test-job:
#  stage: test
#  script:

deploy-job:
  stage: deploy
  script:
    - docker compose up -d