services:
  comments_service:
    container_name: comments
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${EXTERNAL_APP_PORT}:8000"
    env_file:
      - .env.dev
    depends_on:
      - mongo
  mongo:
    image: mongo:7.0.3
    container_name: comments_mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: